backend:
  name: git-gateway
  branch: main

media_folder: "images/gallery"
public_folder: "/images/gallery"

collections:
  - name: "gallery"
    label: "Gallery Posts"
    folder: "_data/gallery"
    create: true
    fields:
      - { name: "image", label: "Image", widget: "image" }
      - { name: "caption", label: "Caption", widget: "string" }